version: '3.4'

services:
  registration.api:
    image: ${DOCKER_REGISTRY-}registrationapi
    build:
      context: .
      dockerfile: Dockerfile
    command: dotnet run
    ports:
      - "80"
      - "443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    networks:
      - network-unblock
networks:
  network-unblock:
    driver: bridge