version: '3.4'

services:
  registration.api:
    image: ${DOCKER_REGISTRY-}registrationapi
    build:
      context: .
      dockerfile: Dockerfile
    command: dotnet run
    ports:
      - 8080:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - network-unblock
networks:
  network-churchmanager:
    driver: bridge