version: '3.4'

services:
  churchmanager:
    container_name: churchmanager
    build:
      context: ./
      dockerfile: Dockerfile
    command: dotnet run
    ports:
      - 8181:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    
    networks:
      - netchurchmanager

networks:
  netchurchmanager:
    driver: bridge