sonar.projectKey=church-key-sonar
sonar.projectName=Church Cashflow Registration
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.login=sqp_93d83c035fb1ba701e366b6cf1e9a0ca8e374901

sonar.sources=.
sonar.exclusions=**/bin/**,**/obj/**,.vscode/**,.claude/**,.git/**,**/packages/**
sonar.tests=./Test
sonar.test.inclusions=**/*Test*.cs,**/*Tests.cs
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
