// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Regristration.Repository;

#nullable disable

namespace Registration.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230405031444_InitialDataBasetithes")]
    partial class InitialDataBasetithes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Registration.DomainBase.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Additional")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Additional");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("City");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Country");

                    b.Property<string>("District")
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("District");

                    b.Property<int>("Number")
                        .HasMaxLength(6)
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("State");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Street");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("ZipCode");

                    b.HasKey("Id");

                    b.ToTable("Address", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Additional = "",
                            City = "São Lourenço",
                            Country = "Brasil",
                            District = "Centro",
                            Number = 780,
                            State = "Minas Gerais",
                            Street = "Rua Dr Ribeiro da Luz",
                            ZipCode = "37470-000"
                        },
                        new
                        {
                            Id = 2,
                            Additional = "Prédio 1",
                            City = "Itaguai",
                            Country = "Brasil",
                            District = "Mesquita",
                            Number = 258,
                            State = "Rio de Janeiro",
                            Street = "Avenida André Chaves",
                            ZipCode = "13710-000"
                        },
                        new
                        {
                            Id = 3,
                            Additional = "Prédio 1",
                            City = "Itaguai",
                            Country = "Brasil",
                            District = "Mesquita",
                            Number = 258,
                            State = "Rio de Janeiro",
                            Street = "Avenida André Chaves",
                            ZipCode = "13710-000"
                        });
                });

            modelBuilder.Entity("Registration.DomainBase.Entities.Church", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnName("Active");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.ToTable("Church", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Acronym = "SLC",
                            AddressId = 1,
                            Name = "CEO São Lourenço"
                        },
                        new
                        {
                            Id = 2,
                            Acronym = "CRT",
                            AddressId = 2,
                            Name = "CEP Cristina"
                        },
                        new
                        {
                            Id = 3,
                            Acronym = "LBR",
                            AddressId = 3,
                            Name = "CEP Lambari"
                        });
                });

            modelBuilder.Entity("Registration.DomainBase.Entities.FirstFruits", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("ChurchId")
                        .HasColumnType("int");

                    b.Property<string>("Competence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Day")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("OfferingKindId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("MemberId");

                    b.HasIndex("OfferingKindId");

                    b.ToTable("FirstFruits");
                });

            modelBuilder.Entity("Registration.DomainBase.Entities.MeetingKind", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnName("Active");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("MeetingKind", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Culto dos dias quinta com oração para libertação",
                            Name = "Culto de Libertação"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Culto do último domingo do mês com ministração da Santa Ceia do Senhor",
                            Name = "Culto de Santa Ceia"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Culto do 4º domingo do mês (quando haver 5 domingos). Culto para convidar o amigo ",
                            Name = "Culto de Centésima Ovelha"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Culto do 2º domingo do mês. Culto das primicias e dizímos",
                            Name = "Culto de Prosperidade"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Culto do 3º domingo do mês. Ofertas serão destinas às missões",
                            Name = "Culto de Missões"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Culto do 1º domingo do mês. Culto de poder, glória e batismo e renovo do Espirito Santo",
                            Name = "Culto do Poder"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Culto em meio a semana. Culto em outros dias da semana. Redes e Eventos",
                            Name = "Culto de Celebração"
                        });
                });

            modelBuilder.Entity("Registration.DomainBase.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnName("Active");

                    b.Property<int>("ChurchId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Code");

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("DATE")
                        .HasColumnName("DateBirth");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Name");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("PostId");

                    b.HasIndex(new[] { "Code" }, "IX_Member_Code")
                        .IsUnique();

                    b.ToTable("Member", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChurchId = 1,
                            Code = "SLC-E7D477",
                            DateBirth = new DateTime(2023, 4, 5, 0, 14, 42, 678, DateTimeKind.Local).AddTicks(1321),
                            Name = "Rodolfo de Jesus Silva",
                            PostId = 2
                        },
                        new
                        {
                            Id = 2,
                            ChurchId = 2,
                            Code = "SLC-63BACD",
                            DateBirth = new DateTime(2023, 4, 5, 0, 14, 42, 678, DateTimeKind.Local).AddTicks(1509),
                            Name = "Kelly Cristina Martins",
                            PostId = 3
                        },
                        new
                        {
                            Id = 3,
                            ChurchId = 1,
                            Code = "SLC-1A2A1C",
                            DateBirth = new DateTime(2023, 4, 5, 0, 14, 42, 678, DateTimeKind.Local).AddTicks(1527),
                            Name = "Manuela Martins de Jesus",
                            PostId = 4
                        });
                });

            modelBuilder.Entity("Registration.DomainBase.Entities.Offering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnName("Active");

                    b.Property<int>("AdultQuantity")
                        .HasColumnType("INT")
                        .HasColumnName("AdultQuantity");

                    b.Property<int>("ChildrenQuantity")
                        .HasColumnType("INT")
                        .HasColumnName("ChildrenQuantity");

                    b.Property<int>("ChurchId")
                        .HasColumnType("INT")
                        .HasColumnName("ChurchId");

                    b.Property<DateTime>("Day")
                        .HasColumnType("DATE")
                        .HasColumnName("Day");

                    b.Property<int>("MeetingKindId")
                        .HasColumnType("INT")
                        .HasColumnName("MeetingKindId");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("OfferingKindId")
                        .HasColumnType("INT")
                        .HasColumnName("OfferingKindId");

                    b.Property<string>("PreacherMemberName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("PreacherMemberName");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("TotalAmount");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("MeetingKindId");

                    b.HasIndex("MemberId");

                    b.HasIndex("OfferingKindId");

                    b.ToTable("Offering", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdultQuantity = 25,
                            ChildrenQuantity = 4,
                            ChurchId = 1,
                            Day = new DateTime(2023, 4, 5, 0, 14, 42, 682, DateTimeKind.Local).AddTicks(7461),
                            MeetingKindId = 1,
                            OfferingKindId = 1,
                            PreacherMemberName = "Pr Antônio Cristino Alves",
                            TotalAmount = 55.90m
                        },
                        new
                        {
                            Id = 2,
                            AdultQuantity = 25,
                            ChildrenQuantity = 4,
                            ChurchId = 2,
                            Day = new DateTime(2023, 4, 5, 0, 14, 42, 682, DateTimeKind.Local).AddTicks(7507),
                            MeetingKindId = 2,
                            OfferingKindId = 2,
                            PreacherMemberName = "Obª Kelly Cristina Martins",
                            TotalAmount = 326.05m
                        },
                        new
                        {
                            Id = 3,
                            AdultQuantity = 25,
                            ChildrenQuantity = 4,
                            ChurchId = 1,
                            Day = new DateTime(2023, 4, 5, 0, 14, 42, 682, DateTimeKind.Local).AddTicks(7511),
                            MeetingKindId = 3,
                            OfferingKindId = 3,
                            PreacherMemberName = "Dcª Iolanda da Silva Souza",
                            TotalAmount = 12.80m
                        });
                });

            modelBuilder.Entity("Registration.DomainBase.Entities.OfferingKind", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnName("Active");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("OfferingKind", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Oferta de amor com pix",
                            Name = "PIX"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Oferta de amor com Cédulas",
                            Name = "Cédulas"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Oferta de amor com cartão crédito/débito",
                            Name = "Crédito/Débito"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Oferta de amor com TED/DOC",
                            Name = "Transferência"
                        });
                });

            modelBuilder.Entity("Registration.DomainBase.Entities.OutFlow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnName("Active");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Amount");

                    b.Property<bool?>("Authorized")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnName("Authorized");

                    b.Property<int>("ChurchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Day")
                        .HasColumnType("DATE")
                        .HasColumnName("Day");

                    b.Property<decimal>("Discount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("Discount");

                    b.Property<decimal>("Interest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("Interest");

                    b.Property<string>("MonthYear")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("MonthYear");

                    b.Property<int>("OutFlowKindId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("TotalAmount");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("OutFlowKindId");

                    b.ToTable("OutFlow", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 100m,
                            Authorized = true,
                            ChurchId = 1,
                            Day = new DateTime(2023, 4, 5, 3, 14, 42, 681, DateTimeKind.Utc).AddTicks(619),
                            Discount = 0m,
                            Interest = 2m,
                            MonthYear = "04/2023",
                            OutFlowKindId = 1,
                            TotalAmount = 0m
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1000.01m,
                            Authorized = true,
                            ChurchId = 2,
                            Day = new DateTime(2023, 4, 5, 3, 14, 42, 681, DateTimeKind.Utc).AddTicks(748),
                            Discount = 0m,
                            Interest = 1.56m,
                            MonthYear = "04/2023",
                            OutFlowKindId = 2,
                            TotalAmount = 0m
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1500.56m,
                            Authorized = true,
                            ChurchId = 3,
                            Day = new DateTime(2023, 4, 5, 3, 14, 42, 681, DateTimeKind.Utc).AddTicks(760),
                            Discount = 20m,
                            Interest = 0.6m,
                            MonthYear = "04/2023",
                            OutFlowKindId = 3,
                            TotalAmount = 0m
                        });
                });

            modelBuilder.Entity("Registration.DomainBase.Entities.OutFlowKind", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnName("Active");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("OutFlowKind", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Conta de Luz",
                            Name = "Energia"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Conta de água",
                            Name = "Água"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Produto de limpeza",
                            Name = "Zeladoria"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Oferta de gratidão para ministrante convidado",
                            Name = "Auxilio Ministrante"
                        });
                });

            modelBuilder.Entity("Registration.DomainBase.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnName("Active");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Post", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Pessoa visitante eventual",
                            Name = "Visitante avulso"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Pessoa visitante frenquente",
                            Name = "Visitante frequente"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Membro batisado com ficha",
                            Name = "Membro"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Membro batisado pertencente ao grupo de louvor",
                            Name = "Levita"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Membro batisado ajudante nos cultos",
                            Name = "Obreiro"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Membro batisado cooperador da obra",
                            Name = "Diacono"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Membro batisado auxiliador do pastor",
                            Name = "Preisbitero"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Membro batisado lider espiritual da Igreja",
                            Name = "Pastor Auxiliar"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Membro batisado lider espiritual e administrativo da Igreja",
                            Name = "Visitante frequente"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Membro batisado lider da cobertura espiritual",
                            Name = "Bispo"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Membro batisado porém transferido sob benção para outra igreja",
                            Name = "Transferido"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Membro batisado porém afastado da igreja",
                            Name = "Desligado"
                        });
                });

            modelBuilder.Entity("Registration.DomainBase.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "LOCAL"
                        },
                        new
                        {
                            Id = 2,
                            Name = "MINISTERIO"
                        });
                });

            modelBuilder.Entity("Registration.DomainBase.Entities.Tithes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnName("Active");

                    b.Property<int>("ChurchId")
                        .HasColumnType("INT")
                        .HasColumnName("ChurchId");

                    b.Property<string>("Competence")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Competence");

                    b.Property<DateTime>("Day")
                        .HasColumnType("DATE")
                        .HasColumnName("Day");

                    b.Property<int>("MemberId")
                        .HasColumnType("INT")
                        .HasColumnName("MemberId");

                    b.Property<int>("OfferingKindId")
                        .HasColumnType("INT")
                        .HasColumnName("OfferingKindId");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("TotalAmount");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("MemberId");

                    b.HasIndex("OfferingKindId");

                    b.ToTable("Tithes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChurchId = 1,
                            Competence = "04/2023",
                            Day = new DateTime(2023, 4, 5, 0, 14, 42, 684, DateTimeKind.Local).AddTicks(5743),
                            MemberId = 1,
                            OfferingKindId = 1,
                            TotalAmount = 33.45m
                        },
                        new
                        {
                            Id = 2,
                            ChurchId = 2,
                            Competence = "03/2023",
                            Day = new DateTime(2023, 4, 5, 0, 14, 42, 684, DateTimeKind.Local).AddTicks(5836),
                            MemberId = 2,
                            OfferingKindId = 1,
                            TotalAmount = 533.45m
                        },
                        new
                        {
                            Id = 3,
                            ChurchId = 1,
                            Competence = "02/2023",
                            Day = new DateTime(2023, 4, 5, 0, 14, 42, 684, DateTimeKind.Local).AddTicks(5841),
                            MemberId = 1,
                            OfferingKindId = 2,
                            TotalAmount = 33.45m
                        });
                });

            modelBuilder.Entity("Registration.DomainBase.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnName("Active");

                    b.Property<int>("ChurchId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(true)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Name");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("PasswordHash");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Code" }, "IX_User_Code")
                        .IsUnique();

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChurchId = 1,
                            Code = "188D55",
                            Name = "Rodolfo de Jesus Silva",
                            PassWord = "12345678",
                            PasswordHash = "10000.9gTGelL87y80rY/GCzg0/w==.R5DGLXILdI1xvHl13KtecpSPzAuZ9X2Dky9aImEjuNc=",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            ChurchId = 2,
                            Code = "29AF92",
                            Name = "Kelly Cristina Martins",
                            PassWord = "12345678",
                            PasswordHash = "10000.z970ALx66p4BQZkRgfrGaA==.COxBMIYj5lJSnYxAPi+ojzBw+0qb9u4LHCvIekeqPio=",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Registration.DomainBase.Entities.Church", b =>
                {
                    b.HasOne("Registration.DomainBase.Entities.Address", "Address")
                        .WithOne()
                        .HasForeignKey("Registration.DomainBase.Entities.Church", "AddressId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("Fk_Church_Address");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Registration.DomainBase.Entities.FirstFruits", b =>
                {
                    b.HasOne("Registration.DomainBase.Entities.Church", "Church")
                        .WithMany("FirstFruits")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Registration.DomainBase.Entities.Member", "Member")
                        .WithMany("FirstFruits")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Registration.DomainBase.Entities.OfferingKind", "OfferingKind")
                        .WithMany("FirstFruits")
                        .HasForeignKey("OfferingKindId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Church");

                    b.Navigation("Member");

                    b.Navigation("OfferingKind");
                });

            modelBuilder.Entity("Registration.DomainBase.Entities.Member", b =>
                {
                    b.HasOne("Registration.DomainBase.Entities.Church", "Church")
                        .WithMany("Members")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("Fk_Member_Church");

                    b.HasOne("Registration.DomainBase.Entities.Post", "Post")
                        .WithMany("Members")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("Fk_Member_Post");

                    b.Navigation("Church");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Registration.DomainBase.Entities.Offering", b =>
                {
                    b.HasOne("Registration.DomainBase.Entities.Church", "Church")
                        .WithMany("Offerings")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("Fk_Offering_Church");

                    b.HasOne("Registration.DomainBase.Entities.MeetingKind", "MeetingKind")
                        .WithMany("Offerings")
                        .HasForeignKey("MeetingKindId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Fk_Offering_MeetingKind");

                    b.HasOne("Registration.DomainBase.Entities.Member", null)
                        .WithMany("Offerings")
                        .HasForeignKey("MemberId");

                    b.HasOne("Registration.DomainBase.Entities.OfferingKind", "OfferingKind")
                        .WithMany("Offerings")
                        .HasForeignKey("OfferingKindId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("Fk_Offering_Offering_Kind");

                    b.Navigation("Church");

                    b.Navigation("MeetingKind");

                    b.Navigation("OfferingKind");
                });

            modelBuilder.Entity("Registration.DomainBase.Entities.OutFlow", b =>
                {
                    b.HasOne("Registration.DomainBase.Entities.Church", "Church")
                        .WithMany("OutFlows")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("Fk_OutFlow-Church");

                    b.HasOne("Registration.DomainBase.Entities.OutFlowKind", "OutFlowKind")
                        .WithMany("OutFlows")
                        .HasForeignKey("OutFlowKindId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("Fk_OutFlowKind-OutFlow");

                    b.Navigation("Church");

                    b.Navigation("OutFlowKind");
                });

            modelBuilder.Entity("Registration.DomainBase.Entities.Tithes", b =>
                {
                    b.HasOne("Registration.DomainBase.Entities.Church", "Church")
                        .WithMany("Tithes")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("Fk_Tithes_Church");

                    b.HasOne("Registration.DomainBase.Entities.Member", "Member")
                        .WithMany("Tithes")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("Fk_Tithes_Member");

                    b.HasOne("Registration.DomainBase.Entities.OfferingKind", "OfferingKind")
                        .WithMany("Tithes")
                        .HasForeignKey("OfferingKindId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("Fk_Tithes_Offering_Kind");

                    b.Navigation("Church");

                    b.Navigation("Member");

                    b.Navigation("OfferingKind");
                });

            modelBuilder.Entity("Registration.DomainBase.Entities.User", b =>
                {
                    b.HasOne("Registration.DomainBase.Entities.Church", "Church")
                        .WithMany("Users")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("Fk_User_Church");

                    b.HasOne("Registration.DomainBase.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("Fk_User_Role");

                    b.Navigation("Church");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Registration.DomainBase.Entities.Church", b =>
                {
                    b.Navigation("FirstFruits");

                    b.Navigation("Members");

                    b.Navigation("Offerings");

                    b.Navigation("OutFlows");

                    b.Navigation("Tithes");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Registration.DomainBase.Entities.MeetingKind", b =>
                {
                    b.Navigation("Offerings");
                });

            modelBuilder.Entity("Registration.DomainBase.Entities.Member", b =>
                {
                    b.Navigation("FirstFruits");

                    b.Navigation("Offerings");

                    b.Navigation("Tithes");
                });

            modelBuilder.Entity("Registration.DomainBase.Entities.OfferingKind", b =>
                {
                    b.Navigation("FirstFruits");

                    b.Navigation("Offerings");

                    b.Navigation("Tithes");
                });

            modelBuilder.Entity("Registration.DomainBase.Entities.OutFlowKind", b =>
                {
                    b.Navigation("OutFlows");
                });

            modelBuilder.Entity("Registration.DomainBase.Entities.Post", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Registration.DomainBase.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
