//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Registration.Resources.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT o.Competence, o.Day, 0 as PreviousBalance, 0 as CurrentBalance, 
        ///k.Description as Title, o.Description, TotalAmount as AmountINputOperation, 0 as AmountOutPutOperation, 0 as TotalOperation, c.Name as Church 
        ///FROM Church c RIGHT JOIN FirstFruits o ON c.Id = o.ChurchId LEFT JOIN OfferingKind k ON o.OfferingKindId = k.Id 
        ///WHERE o.Active = true AND c.Id = {0} 
        ///AND EXTRACT(MONTH FROM o.Day) = {1} AND EXTRACT(YEAR FROM o.DAY) = {2}.
        /// </summary>
        internal static string MonthlyClosingFirstFruits {
            get {
                return ResourceManager.GetString("MonthlyClosingFirstFruits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT o.Competence, o.Day, 0 as PreviousBalance, 0 as CurrentBalance, 
        ///k.Description as Title, o.Description, TotalAmount as AmountINputOperation, 0 as AmountOutPutOperation, 0 as TotalOperation, c.Name as Church 
        ///FROM Church c RIGHT JOIN Offering o ON c.Id = o.ChurchId LEFT JOIN OfferingKind k ON o.OfferingKindId = k.Id 
        ///WHERE o.Active = true AND c.Id = {0} 
        ///AND EXTRACT(MONTH FROM o.Day) = {1} AND EXTRACT(YEAR FROM o.DAY) = {2}.
        /// </summary>
        internal static string MonthlyClosingOffering {
            get {
                return ResourceManager.GetString("MonthlyClosingOffering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT o.Competence, o.Day, 0 as PreviousBalance, 0 as CurrentBalance,  
        ///k.Description as Title, o.Description, 0 as AmountINputOperation, TotalAmount as AmountOutPutOperation, 0 as TotalOperation, c.Name as Church 
        ///FROM Church c RIGHT JOIN OutFlow o ON c.Id = o.ChurchId LEFT JOIN OutFlowKind k ON o.OutFlowKindId = k.Id 
        ///WHERE o.Authorized = true AND o.Active = true AND c.Id = {0} 
        ///AND EXTRACT(MONTH FROM o.Day) = {1} AND EXTRACT(YEAR FROM o.DAY) = {2}.
        /// </summary>
        internal static string MonthlyClosingOutFlow {
            get {
                return ResourceManager.GetString("MonthlyClosingOutFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT o.Competence, o.Day, 0 as PreviousBalance, 0 as CurrentBalance,  
        ///k.Description as Title, o.Description, TotalAmount as AmountINputOperation, 0 as  AmountOutPutOperation, 0 as TotalOperation, c.Name as Church 
        ///FROM Church c RIGHT JOIN Tithes o ON c.Id = o.ChurchId LEFT JOIN OfferingKind k ON o.OfferingKindId = k.Id 
        ///WHERE o.Active = true AND c.Id = {0} 
        ///AND EXTRACT(MONTH FROM o.Day) = {1} AND EXTRACT(YEAR FROM o.DAY) = {2} .
        /// </summary>
        internal static string MonthlyClosingTithes {
            get {
                return ResourceManager.GetString("MonthlyClosingTithes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT m.Name, f.Day, f.Competence, f.TotalAmount, o.Name AS OfferingName 
        ///FROM FirstFruits f LEFT JOIN Member m ON f.MemberId = m.Id 
        ///LEFT JOIN OfferingKind o ON f.OfferingKindId = o.Id 
        ///WHERE f.ChurchId = {0} 
        ///AND EXTRACT(MONTH FROM f.Day) = {1} AND EXTRACT(YEAR FROM f.Day) = {2} AND f.Active = true
        ///ORDER BY m.Name;.
        /// </summary>
        internal static string MonthlyFirstFruits {
            get {
                return ResourceManager.GetString("MonthlyFirstFruits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT o.PreacherMemberName, o.Day, o.Competence, o.TotalAmount, 
        ///o.AdultQuantity, o.ChildrenQuantity, (o.AdultQuantity + o.ChildrenQuantity) AS PeopleQuantity, m.Name AS MeetingName, f.Name AS OfferingName 
        ///FROM Offering o LEFT JOIN MeetingKind m ON o.MeetingKindId = m.Id LEFT JOIN OfferingKind f ON o.OfferingKindId = f.Id 
        ///WHERE o.ChurchId = {0} AND EXTRACT(MONTH FROM o.Day) = {1} AND EXTRACT(YEAR FROM o.Day) = {2} AND o.Active = true 
        ///ORDER BY o.Day;.
        /// </summary>
        internal static string MonthlyOffering {
            get {
                return ResourceManager.GetString("MonthlyOffering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT m.Name, t.Day, t.Competence, t.TotalAmount FROM Tithes t LEFT JOIN Member m ON t.MemberId = m.Id WHERE t.ChurchId = {0} 
        ///AND EXTRACT(MONTH FROM t.Day) = {1} AND EXTRACT(YEAR FROM t.Day) = {2} AND t.Active = true 
        ///ORDER BY m.Name;.
        /// </summary>
        internal static string MonthlyTithers {
            get {
                return ResourceManager.GetString("MonthlyTithers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT &apos;&apos; as Competence, &apos;0001-01-01&apos; as Day, 0 as PreviousBalance, FinalValue as CurrentBalance,  &apos;fisrt field month minus 1&apos; Description, &apos;&apos; Description, 0 as AmountINputOperation, 0 as AmountOutPutOperation, 0 as TotalOperation, &apos;&apos; as Church 
        ///FROM MonthWork M WHERE M.ChurchId = {0} AND M.YearMonth = {1}{2}.
        /// </summary>
        internal static string MonthlyValueMonthMinus1 {
            get {
                return ResourceManager.GetString("MonthlyValueMonthMinus1", resourceCulture);
            }
        }
    }
}
