# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: CI churchManager

on:
  push:
    branches: [ "main", "master", "feat/continuos_integration" ]
  pull_request:
    branches: [ "main", "master", "feat/continuos_integration" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./Registration/src/Application/Registration.API/Registration.API.csproj

    - name: Build with dotnet
      run: dotnet build ./Registration/src/Application/Registration.API/Registration.API.csproj --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal
